### ISSUE TITLE
use `docker_image` hook

### ISSUE THREAD

**Issue by eggplants** [pecigonzalo/pre-commit-shfmt#8]
<https://pre-commit.com/#docker_image>

Note: with `docker` hook:

>pre-commit will automatically mount the repository source as a volume using -v $PWD:/src:rw,Z and set the working directory using --workdir /src.

And `docker_image` [too](https://github.com/pre-commit/pre-commit/blob/7f189260e63243459bb1f19281e36242e264ea2f/pre_commit/languages/docker_image.py#L20).

```yaml
- id: shell-fmt
  name: shfmt
  description: Rewrites all shell scripts to a canonical format.
  entry: hub.docker.com/mvdan/shfmt
  language: docker_image
  types:
    - file
    - shell
  exclude_types:
    - zsh
  args:
    - -w
    - -s
    - -l
    - -i
    - "4"
```
